export interface IPharmacy {    
    ApothekenID: number,
    Kundennummer: string,
    Betriebsstaette: string,
    ApothekenName: string,
    Strasse: string,
    Postleitzahl: string,
    Ort: string,
    Telefonnummer: string,
    Faxnummer: string,
    EMail: string,
    Nachname: string,
    Vorname: string,
    Titel: string,
    Geburtsdatum: string,
    Aktiv: string,
    Bemerkung: string,
    Gebiet: string,
    Gebietsleiter: string,
    IMS_Kreis_ID: string,
    Kunden_Klasse: string,
    IDFNummer: string,
    Noweda_Kunde: string,
    Kundennummer_vorgaenger: string,
    Vorgaenger_gueltig_ab: string,
    Kundennnummer_nachfolger: string,
    Nachfolger_gueltig_ab:string,
    ImportDatum: string
}